export const USER_AUTHENTICATED_REQUESTED = 'auth/USER_AUTHENTICATED_REQUESTED';
export const USER_AUTHENTICATED_FULFILLED = 'auth/USER_AUTHENTICATED_FULFILLED';
export const USER_AUTHENTICATED_FAILED = 'auth/USER_AUTHENTICATED_FAILED';
