export const USER_AUTHENTICATED_REQUESTED = 'auth/USER_AUTHENTICATED_REQUESTED';
export const USER_AUTHENTICATED_FULFILLED = 'auth/USER_AUTHENTICATED_FULFILLED';
export const USER_AUTHENTICATED_FAILED = 'auth/USER_AUTHENTICATED_FAILED';

export const USER_LOGOUT = 'auth/USER_LOGOUT';

export const USER_INFO_REQUESTED = 'user/USER_INFO_REQUESTED';
export const USER_INFO_FULFILLED = 'user/USER_INFO_FULFILLED';
export const USER_INFO_FAILED = 'user/USER_INFO_FAILED';

export const USER_CHANGE_LANGUAGE = 'auth/USER_CHANGE_LANGUAGE';
